---
# Variables specific to RHEL servers
os_family: RedHat
package_manager: yum

# SSH connection settings (vault encrypted)
ansible_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66646337316663306330386437336661383061636231393365636630333138363830663833633237
          6635323435386332396638616462323266333536643661330a633537383138313463633636366331
          34646538623238623834326431613764313539316338643338343337336561393864393834353536
          3639303264653732300a333538633266626631363862633166383364636534353763353263396436
          3961
ansible_ssh_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64393166646633323334626466613935623336626130663435326665636633393265333637383736
          3666393065326464616561316536306137306138333830380a383261373663653430616434623230
          32383866393263346132613335653466346564363138396639666232356537663434396232386666
          3963346637303763630a353038303435373266396535303564323964616664326530303664313836
          3031

# Privilege escalation (sudo) settings
ansible_become: yes
ansible_become_method: sudo
ansible_become_user: root
ansible_become_pass: "{{ ansible_ssh_pass }}"

